### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by hatem-u** [code-biscuits/nvim-biscuits#1]
![](https://i.imgur.com/wVREzgT.png)

You can see that it says `return MaterialApp(` which should just be either `return MaterialApp` or `MaterialApp`, also in the bottom it is putting the whole definition of the class which looks odd.

This is how it looks using VS Code with the official Flutter plugin:

![](https://i.imgur.com/uHBnJRB.png)

That's not really important as much as this next thing which is really Flutter/Dart specific, I think. Here several things can be improved:

![](https://i.imgur.com/sf5FQP3.png)

1.  `<Widget>[` This is missing the closing bracket.
2.  `child: Column(` this should be just `Column`
3.  `body: Center(` same as the previous
4.  you can see `FloatingActionButton` isn't showing the biscuit (with or without the comment) which is kind of weird because it is the same as the previous Column and Center classes.

Official Flutter plugin:

![](https://i.imgur.com/MIQykxl.png)

**Comment by akinsho** [comment]
@HatEmU closing tags for flutter are actually provided via the language server since the treesitter grammar won't identify those nodes correctly (I know since I helped add the treesitter dart grammar a while ago) I've actually created a plugin that does this and other things for flutter over in https://github.com/akinsho/flutter-tools.nvim.

This is a great plugin for a wider range of languages though, just thought I'd mention

**Comment by cmgriffing** [comment]
After revisiting this again, please use akinsho's plugin if you desire more specific (and more correct) Dart/Flutter annotations.

This gave me an idea just now though:
> You can see that it says return MaterialApp( which should just be either return MaterialApp or MaterialApp

I think it might make sense to have a global and per language character/word filter as configuration. Then users could customize which characters or words show up. ie: "(" or "return".

Creating a new issue for that and closing this.

https://github.com/code-biscuits/nvim-biscuits/issues/29
